CREATE TABLE phone_data
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    phone   VARCHAR(255),
    CONSTRAINT pk_phone_data PRIMARY KEY (id)
);

ALTER TABLE phone_data
    ADD CONSTRAINT uc_phone_data_phone UNIQUE (phone);

ALTER TABLE phone_data
    ADD CONSTRAINT FK_PHONE_DATA_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);